# Generated by Django 3.0.6 on 2020-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customusermodel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
