# Generated by Django 3.0.6 on 2020-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200603_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='last_signed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
